"""
Phase 10 — Conversation Data Analytics

IMPORTANT: This repository has no real user traffic yet (it hasn't been
deployed). To demonstrate the analytics pipeline works correctly, this
script sends a batch of sample messages THROUGH THE REAL HYBRID PIPELINE
(flask_app/pipeline.py) to generate genuine log rows in
flask_app/logs/conversations.csv, then analyzes those real logs.

This is explicitly a DEMO/SIMULATION for illustrating the analytics
pipeline, not real user data. Once deployed, flask_app/logs/conversations.csv
will accumulate real conversation logs and this same analysis script can be
re-run against real data — the code does not change, only its input does.

Run: python notebooks/09_conversation_analytics.py
"""

import os
import sys
import random

import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, "flask_app"))

LOG_PATH = os.path.join(BASE_DIR, "flask_app", "logs", "conversations.csv")
PLOTS_DIR = os.path.join(BASE_DIR, "reports", "plots")
REPORT_PATH = os.path.join(BASE_DIR, "reports", "conversation_analytics.md")

os.makedirs(PLOTS_DIR, exist_ok=True)

SAMPLE_MESSAGES = [
    "I feel so anxious about tomorrow", "I'm really happy today",
    "I feel disgusted by what happened", "nothing feels good lately",
    "I'm not sure what I'm feeling", "that came out of nowhere, I'm shocked",
    "I'm furious about this", "I feel scared right now",
    "just checking in", "I feel fantastic this morning",
    "I feel really low and empty", "this is disgusting honestly",
    "I can't believe that just happened", "I'm on edge about the exam",
    "feeling okay I guess", "I'm thrilled about the news",
    "I feel numb and distant", "that was surprising to hear",
    "I'm irritated with everything today", "I feel uneasy about this decision",
]


def generate_demo_traffic(n_sessions=15, msgs_per_session=(1, 4)):
    from pipeline import get_pipeline
    import uuid

    pipeline = get_pipeline()
    random.seed(42)

    for _ in range(n_sessions):
        session_id = str(uuid.uuid4())
        n_msgs = random.randint(*msgs_per_session)
        for _ in range(n_msgs):
            msg = random.choice(SAMPLE_MESSAGES)
            pipeline.handle_message(msg, session_id=session_id)


def analyze():
    logs = pd.read_csv(LOG_PATH)

    total_messages = len(logs)
    unique_sessions = logs["session_id"].nunique()
    msgs_per_session = logs.groupby("session_id").size()

    emotion_dist = logs["predicted_emotion"].value_counts(dropna=True)
    response_type_dist = logs["response_type"].value_counts()
    faq_match_rate = (logs["response_type"] == "faq_match").mean()
    fallback_rate = (logs["response_type"] == "fallback").mean()
    avg_faq_similarity = logs["faq_similarity_score"].mean()
    latency_stats = logs["latency_seconds"].describe()
    confidence_stats = logs["classifier_confidence"].describe()
    input_length_stats = logs["input_length"].describe()

    # Emotion transitions within a session (order by timestamp)
    logs_sorted = logs.sort_values(["session_id", "timestamp"])
    transitions = []
    for _, group in logs_sorted.groupby("session_id"):
        emotions = group["predicted_emotion"].dropna().tolist()
        for i in range(len(emotions) - 1):
            transitions.append((emotions[i], emotions[i + 1]))
    transition_counts = pd.Series(transitions).value_counts() if transitions else pd.Series(dtype=int)

    # ---- Plots ----
    plt.figure(figsize=(8, 5))
    emotion_dist.plot(kind="bar", color="#6c63ff")
    plt.title("Emotion Distribution (demo traffic)")
    plt.ylabel("Count")
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, "analytics_emotion_distribution.png"), dpi=150)
    plt.close()

    plt.figure(figsize=(6, 5))
    response_type_dist.plot(kind="pie", autopct="%1.1f%%")
    plt.title("Response Type Breakdown")
    plt.ylabel("")
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, "analytics_response_type.png"), dpi=150)
    plt.close()

    plt.figure(figsize=(8, 5))
    plt.hist(logs["latency_seconds"].dropna(), bins=20, color="#87ceeb", edgecolor="black")
    plt.title("Response Latency Distribution")
    plt.xlabel("Seconds")
    plt.tight_layout()
    plt.savefig(os.path.join(PLOTS_DIR, "analytics_latency.png"), dpi=150)
    plt.close()

    report = f"""# Conversation Analytics

⚠️ **This analysis runs on simulated demo traffic** ({total_messages} messages
across {unique_sessions} sessions), generated by sending sample messages
through the real hybrid pipeline (`flask_app/pipeline.py`) — these are
**application-level conversational statistics**, not clinical measurements,
and not real user data. Once deployed, this exact script analyzes real
accumulated logs from `flask_app/logs/conversations.csv` without modification.

## Volume

- Total messages: **{total_messages}**
- Unique sessions: **{unique_sessions}**
- Messages per session — mean: **{msgs_per_session.mean():.2f}**, max: **{msgs_per_session.max()}**

## Emotion Distribution

{chr(10).join(f"- {e}: {c}" for e, c in emotion_dist.items())}

![Emotion Distribution](plots/analytics_emotion_distribution.png)

## FAQ vs. Fallback

- FAQ match rate: **{faq_match_rate:.2%}**
- Fallback rate: **{fallback_rate:.2%}**
- Average FAQ similarity score: **{avg_faq_similarity:.4f}**

![Response Type Breakdown](plots/analytics_response_type.png)

## Latency

{chr(10).join(f"- {k}: {v:.5f}s" for k, v in latency_stats.items())}

![Latency Distribution](plots/analytics_latency.png)

## Classifier Confidence (on non-FAQ-matched messages)

{chr(10).join(f"- {k}: {v:.4f}" for k, v in confidence_stats.dropna().items())}

## Input Length

{chr(10).join(f"- {k}: {v:.2f}" for k, v in input_length_stats.items())}

## Emotion Transitions (within-session, consecutive messages)

{chr(10).join(f"- {a} → {b}: {c}" for (a, b), c in transition_counts.items()) if len(transition_counts) else "(Not enough multi-message sessions in this demo batch to compute transitions.)"}
"""

    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"Analyzed {total_messages} messages across {unique_sessions} sessions.")
    print(f"Report written to: {REPORT_PATH}")


if __name__ == "__main__":
    if not os.path.exists(LOG_PATH) or len(pd.read_csv(LOG_PATH)) < 10:
        print("Generating demo traffic through the real pipeline...")
        generate_demo_traffic()
    analyze()
